### ISSUE TITLE
Support Speaker on/off for Classic Variant to suppress Noise on startup and shutdown

### ISSUE THREAD

**Issue by boerge1** [tonuino/TonUINO-TNG#126]
Additional HW connected to D6 is necessary for this

**Comment by boerge1** [comment]
pull request #128 created

**Comment by boerge1** [comment]
pull request #128 merged

**Comment by GuteLaune** [comment]
The topic in the forum is https://discourse.voss.earth/t/geraeusch-beim-start-der-box-allerdings-nicht-bei-jedem-start/1357/34?u=gute_laune.
