### ISSUE TITLE
Restart last playback if Play/Pause pressed

### ISSUE THREAD

**Issue by tuetenk0pp** [tonuino/TonUINO-TNG#142]
Once an album is finished playing, I would like to restart the album from the beginning with a press on play/pause.

At the moment, I have to remove the tag and place it again to be able to restart the album.

**Comment by boerge1** [comment]
Could you please test it on branch [issue_142](https://github.com/tonuino/TonUINO-TNG/tree/issue_142)? 
I will ask the community whether it should be activated for all or via #define.

**Comment by tuetenk0pp** [comment]
Hi @boerge1, I can confirm it works on AiO Plus :) thank you so much!

**Comment by boerge1** [comment]
pull request #145 created

**Comment by boerge1** [comment]
pull request #145 merged
