### ISSUE TITLE
Shortcut at startup doesn't work

### ISSUE THREAD

**Issue by dl9sec** [tonuino/TonUINO-TNG#16]
Hi,
I used the latest sourcecode (TonUINO Classic, 5 buttons) and selected a file (folder 1, title 1) to be played once at startup in the admin mode at shortcuts.
Box told me, that it is stored, but the title isn't played at startup of the box, just a "pling" sound is played...

Regards, Thorsten

**Comment by boerge1** [comment]
Created branch 'issue_016' with a fix. @dl9sec could you please test it?
Created Pull Request #17

**Comment by dl9sec** [comment]
Thanks for the fast response.
Will give you a feedback tomorrow (TonUINO currently in use  by my son to fall asleep :-D )...
Regards, Thorsten

**Comment by dl9sec** [comment]
The "issue_016"-branch seems to fix the problem.
Thank you.
Regards, Thorsten
