### ISSUE TITLE
Improve Rorary Encoder implementation (also for NANO and optional for next/previous)

### ISSUE THREAD

**Issue by boerge1** [tonuino/TonUINO-TNG#173]
* if interrupt pin is not supported (NANO) use a timer ISR (200 Hz) with polling
* optional feature: if one click is done in one second interpret it as next/previous

Thanks @DeKi90 for the idea

**Comment by boerge1** [comment]
pull request #174 created

**Comment by DeKi90** [comment]
Thanks @boerge1.
I didn't spot the existing timer implementation, that is great.
Can you clarify why you chose to make the volume and long_press timeouts independent?

**Comment by boerge1** [comment]
Because they have different meaning. The vol timer is to show, that the last change was a vol change and until it expires, every change should also a vol change (also if pos ==1). So after it expires there will be no remaining pos! =0) and no up/down cmd will be raised afterwards without turning the rot encoder.
With this implementation we have no wait vor the vol cmd, right after two clicks the vol will be changed.

**Comment by DeKi90** [comment]
Ah.. that makes sense, yes.
My approach was to handle this the same way as the buttons to avoid small users jamming the volume up all the time. But most likely this input is for more dexterous users in the first place :-D

**Comment by boerge1** [comment]
@DeKi90 did you already test my implementation?

**Comment by boerge1** [comment]
pull request #174 merged
