### ISSUE TITLE
Add offline pyton text-to-speech engine pyttsx3 

### ISSUE THREAD

**Issue by SteRoh** [tonuino/TonUINO-TNG#20]
As a consumer I want to create all audio files automatically without any account usage (aws or google cloud).

OS: Platform independent

Python pyttsx3 is a text-to-speech conversion library in Python. Unlike alternative libraries, it works **offline**.

https://github.com/nateshmbhat/pyttsx3

Included TTS engines:

sapi5
nsss
espeak

**Comment by boerge1** [comment]
replaced issue by better variant #62
