### ISSUE TITLE
Feature Request: Persist MP3 <> NFC Tag Assignment on SD Card?

### ISSUE THREAD

**Issue by stevenengland** [tonuino/TonUINO-TNG#230]
Hello Tonuino community,

I'm working with the Tonuino for the first time and am still trying to tie up some loose ends. Apart from all the compliments I could spread, there is one point that is really worrying me at the moment. Apparently the MP3 <> NFC tag link has been outsourced to the NFC tag itself. In other words, the information about which OS version, which folder and which playback type should be assigned to the NFC tag. I have read that this has been removed from the EEPROM because the memory there is limited. Is this correct? Would it be feasible to persist this mapping on the SD card instead? Or to put it another way: Is there a technical problem with this?

-  The module for decoding MP3s does not allow anything other than MP3s on the SD card? I conclude this from the SD card management tools, which erase OS-specific files.
- Reading a larger file from the SD card (whether once for further use in the RAM or each time an NFC tag is recognized) is not easy for the Arduino to handle?
- ...?

The advantage would be that you can wildly change the structure on the SD card without having to rewrite dozens of SD cards afterwards. Furthermore, the management SD card/tag assignment could be done by just one tool in exactly one place and quite quickly.

I don't have much practical experience yet in terms of managing content of a tonuino. But I think that I will want to touch the structure on the SD card more often due to the children's rapidly changing interests. But maybe it won't be exactly like that ;)

**Comment by boerge1** [comment]
As discussed [here](https://discourse.voss.earth/t/feature-request-zuordnung-mp3-nfc-tag-auf-sd-karte-ablegen) this is not possible to implement and in my opinion not necessary.
