### ISSUE TITLE
Pololu sometimes does not switch off in sleep mode

### ISSUE THREAD

**Issue by Paero** [tonuino/TonUINO-TNG#238]
In my case, when putting the Arduino in sleep mode the Pololu stayed on or turned on again very quickly in many cases and the Arduino could not be woken up again without manually cutting power. I suspect some weird timing and/or interference issues due to the Arduino standby preventing the D7 Pin to properly switch to HIGH, which probably only happens with some hardware setups. 
Since reducing the power draw to trigger a power banks automatic shutdown is only needed for setups without a Polulu I put safeguards around that code section, which fixed that issue for me. Increasing the time delay after setting the Pin may also work.
Software version: 3.2.0

    void Tonuino::shutdown() {
        LOG(standby_log, s_info, F("power off!"));
    
    #ifdef NEO_RING
        ring.call_on_sleep();
        delay(500);
    #endif
    
    #if defined SPKONOFF
        digitalWrite(ampEnablePin, getLevel(ampEnablePinType, level::inactive));
        delay(1000);
    #endif
    
        // enter sleep state
        digitalWrite(shutdownPin, getLevel(shutdownPinType, level::active));
        delay(500);
    
        // http://discourse.voss.earth/t/intenso-s10000-powerbank-automatische-abschaltung-software-only/805
        // powerdown to 27mA (powerbank switches off after 30-60s)
    #if not defined USE_POLOLU_SHUTDOWN
        chip_card.sleepCard();
        mp3.sleep();
    
        set_sleep_mode(SLEEP_MODE_PWR_DOWN);
        cli();  // Disable interrupts
        sleep_mode();
    #endif
    }

**Comment by boerge1** [comment]
Yes, I will make this change in the next release.
But the delay of 1/2 second shoul be enough to switch off the pololu, shouldn't it?

**Comment by Paero** [comment]
I agree and i am still not sure why it happened for me, and it probably works for most people. Maybe the Arduino stays alive long enough after the Polulu cuts power that it can still go into sleep mode and cause some voltage spikes or interferences that can turn the Polulu on again.

**Comment by boerge1** [comment]
pull request #243 created

**Comment by boerge1** [comment]
pull request #243 merged
