### ISSUE TITLE
Revise Button behavior

### ISSUE THREAD

**Issue by boerge1** [tonuino/TonUINO-TNG#28]
Proposal: change the button behavior the same as the fork of [Thomas-Lehnert](https://discourse.voss.earth/t/tester-gesucht-tonuino-3-1/12086/62): 
```
three Button
============
                                                      vol/next-prev inverted
           admin-menu  idle        pause       play         play
--------------------------------------------------------------------------
pause      select                  play        pause        pause
pauseLong  end adm     shutdown    shutdown    track#       track#
up         next                                next         vol++
upLong     next 10     shortcut2   shortcut2   vol++ cont.  next
down       prev                                prev         vol--
downLong   prev 10     shortcut3   shortcut3   vol-- cont.  prev
updownLong             shortcut1   shortcut1

five Button
===========
vol/next-prev inverted has no effect for 5 Buttons

           admin-menu  idle        pause       play
-----------------------------------------------------------
pause      select                  play        pause
pauseLong  end adm     shutdown    shutdown    track#
up         next                                next
upLong     next 10     shortcut2   shortcut2   next 10
down       prev                                prev
downLong   prev 10     shortcut2   shortcut3   prev 10
updownLong             shortcut1   shortcut1
four       next                                vol++
fourLong   next 10                             vol++ cont.
five       prev                                vol--
fiveLong   prev 10                             vol-- cont.
```
comments are welcome

edit: changed table above according to comments on http://discourse.voss.earth/t/tester-gesucht-tonuino-3-1/12086/90?u=boerge1
edit: changed table again (add continuously increase/decrease volume if long press)
edit: implement shutdown on pauseLong (the shortcut is now on updownLong

**Comment by boerge1** [comment]
Made a first implementation on branch 'issue_028'.

**Comment by jochenberger** [comment]
I tried that but I wish we had
3-btn, Play upLong vol++ cont. and Play downLong vol-- cont. (see #24 and https://github.com/tonuino/TonUINO-TNG/commit/d75ada2a4f700a4a4dfb7a10f49c10bde573a22b#r90991535).

**Comment by boerge1** [comment]
Created pull request #30

**Comment by jochenberger** [comment]
> vol/next-prev inverted has no effect for 5 Buttons

Should the respective sections be removed from the admin menu then?

**Comment by jochenberger** [comment]
> I tried that but I wish we had 3-btn, not inverted: Play upLong vol++ cont. and Play downLong vol-- cont. (see #24 and [d75ada2#r90991535](https://github.com/tonuino/TonUINO-TNG/commit/d75ada2a4f700a4a4dfb7a10f49c10bde573a22b#r90991535)).

Oh, you already did that, I didn't notice until I just tried to change the behavior. :laughing: Maybe you should say so in the comment.

**Comment by boerge1** [comment]
Pull request #30 is merged
