### ISSUE TITLE
Update TTS scripts to latests versions

### ISSUE THREAD

**Issue by seisfeld** [tonuino/TonUINO-TNG#7]
Source: https://github.com/seisfeld/TonUINO/tree/master/tools

**Comment by boerge1** [comment]
The scripts already updated
Changed now the file 'audio_messages_de.txt'

**Comment by boerge1** [comment]
created pull request #14

**Comment by seisfeld** [comment]
> The scripts already updated

I don't see this. I only know Thorsten watend to work on this to merge his one addition with the version from my Repo.

**Comment by boerge1** [comment]
Done merging. Please review and test.

**Comment by boerge1** [comment]
resolved by pull request #57
