### ISSUE TITLE
Support DF Player GD3200B

### ISSUE THREAD

**Issue by boerge1** [tonuino/TonUINO-TNG#79]
Use Solution from here: 

[Probleme mit dem DFPlayer Mini](https://discourse.voss.earth/t/probleme-mit-dem-dfplayer-mini/12203)

**Comment by AlmightyFrog** [comment]
Maybe it would be nice to add a global config flag which can be used to switch between the different implementation to handle the quirks of the different chips, e.g. including MH2024K-16SS which seems to be popular also besides GD3200B.

**Comment by boerge1** [comment]
pull request #87 created

**Comment by boerge1** [comment]
pull request #87 merged
