### ISSUE TITLE
Measure Battery Voltage Feature

### ISSUE THREAD

**Issue by seisfeld** [tonuino/TonUINO-TNG#9]
On AiO Plus the hardware supports to measure the Battery Voltage. Calculating percent remaining is probably kinda difficult due to the very flat discharge curve of LiFePO4. But a warning at a very low level could be considered. If implemented we need to consider both LiFePO4 and LiPo voltages.

**Comment by boerge1** [comment]
@seisfeld Better to close this as "not planed" and not as "completed"
