### ISSUE TITLE
location for platfrom.txt on macOS does not exist

### ISSUE THREAD

**Issue by pa-braun** [tonuino/TonUINO-TNG#93]
according to README.md, location of platform.txt is: /Applications/Arduino.app/Contents/Java/arduino/hardware/avr

but with macOS 13.3.1 and Arduino IDE 2.1.0, the location /Applications/Arduino.app/Contents/Java does not exist. I think the correct location is this one: 
~/Library/Arduino15/packages/arduino/hardware/avr

**Comment by boerge1** [comment]
created pull request #94

**Comment by boerge1** [comment]
merged pull request #94
