### ISSUE TITLE
Use new DFPlayer Mini Mp3 v1.2.1 Library

### ISSUE THREAD

**Issue by tschambe** [tonuino/TonUINO-TNG#99]
Hi everyone,

first of all thanks for your awesome work.
The version of the library "DFPlayer Mini Mp3 by Makuna" mentioned in the README.md (with 1.1.0) does not work with the current firmware.
I spent quite some time today with debugging this but a switch to the most recent version 1.2.1 fixed all my problems.
Maybe it is worth checking if this problem also occurs in your setup and then modify the Readme accordingly.
Thanks again and all the best,
Thomas

**Comment by boerge1** [comment]
What df player you are using? Please have a look at the chip.
We tried version 1.2.0 and there were problems. I will test now the version 1.2.1

**Comment by boerge1** [comment]
Tested version 1.2.1 with my HW. 

Classic: runs without error, but also version 1.1.0 was running without any error
AiO plus: has problems playing tracks in the mp3 folder, with version 1.1.0 all is running without any error

Will ask other in the forum [TonUINO](https://discourse.voss.earth/)
Until clarification remain on version 1.1.0

**Comment by boerge1** [comment]
Tested version 1.2.1 with my HW. 

Classic: runs without error, but also version 1.1.0 was running without any error
AiO plus: has problems playing tracks in the mp3 folder, with version 1.1.0 all is running without any error

Will ask other in the forum [TonUINO](https://discourse.voss.earth/)
Until clarification remain on version 1.1.0

**Comment by boerge1** [comment]
@tschambe Could you please test the branch issue_099 with your DFPlayer? (Of course with the library version 1.2.1)
I did a change that this new version is also working with the other DFPlayer that are used for TonUINO.

**Comment by tschambe** [comment]
Yes I will do this on Monday (I don't have access to the hardware right now...). Thanks for the fix!

**Comment by tschambe** [comment]
So I finally checked it. Your fix works great with my hardware. Library Version 1.2.1
